<?php
/**
 * @file
 * Install, update and uninstall functions for the Fitvids module.
 */

/**
 * Enable the module
 */
function fitvids_enable() {
  $path = backdrop_get_path('module', 'fitvids') . '/js/jquery.fitvids.js';
  $installed = file_exists($path);
  if (!$installed) {
    $message = t('There was a problem with installation. The Fitvids plugin is not where it should be.');
    backdrop_set_message(filter_xss_admin($message), $type = 'warning');
  }
  else {
    $message = t('Fitvids is now installed. Configure the module !fitvids-configuration.', array(
      '!fitvids-configuration' => l(t('here'), 'admin/config/media/fitvids'),
    ));
    backdrop_set_message(filter_xss_admin($message));
  }
}
